# This pipeline automates the deployment process using Terraform and AWS.
# It includes the following steps:
# 1. Login to AWS using credentials stored in Azure DevOps pipeline variables.
# 2. Initialize Terraform in the working directory.
# 3. Generate a Terraform plan to show the actions Terraform will take.
#
# Trigger:
# - The pipeline is triggered by changes to the 'main' branch.
#
# Pool:
# - The pipeline runs on the latest Ubuntu virtual machine image.
#
# Steps:
# - Login to AWS: Configures the AWS CLI with credentials from pipeline variables.
# - Terraform Init: Initializes Terraform, downloading necessary provider plugins.
# - Terraform Plan: Generates an execution plan for the Terraform configuration.


trigger:
- main

pool: wsl-pool

# variables:
#   theKeypair: '$(MY_KEYPAIR)'

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.9.8'

- script: |
    echo "##vso[task.setvariable variable=TF_VAR_ssh_key]$(ssh_key)"
  displayName: 'Set Terraform SSH Key Variable'

- script: |
      echo "The TF_VAR_variables: $(test_env_var)"
      # TF_VAR_test_var = $(test_env_var)
      # export TF_VAR_test_var
      printenv | grep TF_VAR
  displayName: 'Set environment variable'
    
# - task: InstallSSHKey@0
#   inputs:
#     knownHostsEntry: $(known_hosts)
#     # sshKeySecureFile: 'id_rsa.pub'
#     sshPublicKey: '$(MY_KEYPAIR)'
#     sshKeySecureFile: 'id_rsa'

- script: |
    echo "Logging into AWS..."
    aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
    aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
    aws configure set default.region us-east-1
  displayName: 'Login to AWS'

# - script: |
#     export TF_VAR_keypair='$(MY_KEYPAIR)'
#   displayName: 'Init ssh key from an environment variable'

- script: |
    echo "Initializing Terraform..."
    terraform init 
  displayName: 'Terraform Init'
  env:
    TF_VAR_ssh_key: $(TF_VAR_ssh_key)

- script: |
    echo "Planning Terraform..."
    terraform plan -out="out.tfplan"
  displayName: 'Terraform Plan'
  env:
    TF_VAR_ssh_key: $(TF_VAR_ssh_key)
  
- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    artifact: 'Terraform_space'